name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      #- uses: actions/checkout@v2
      
      - name: Script
        run: bash job.sh
